version: '3.7'

services:

  sshd:
    
    build: sshd

    ports:
      - "122:22" # TCP Port   - ssh

    volumes:
      # So that Traefik can listen to the Docker events
      - "./persist/sshsavedhostkeys:/etc/sshsavedhostkeys:rw"
      - "./persist/shelluserssh:/home/shelluser/.ssh:rw"

    logging:
      options:
        max-size: "10m"
        max-file: "3"

    container_name: sshd

    entrypoint: /entrypoint.sh
